/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DeleteTestEntity1Args } from "./DeleteTestEntity1Args";
import { TestEntity1FindManyArgs } from "./TestEntity1FindManyArgs";
import { TestEntity1FindUniqueArgs } from "./TestEntity1FindUniqueArgs";
import { TestEntity1 } from "./TestEntity1";
import { TestEntity1Service } from "../testEntity1.service";

@graphql.Resolver(() => TestEntity1)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class TestEntity1ResolverBase {
  constructor(
    protected readonly service: TestEntity1Service,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "TestEntity1",
    action: "read",
    possession: "any",
  })
  async _testEntity1sMeta(
    @graphql.Args() args: TestEntity1FindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [TestEntity1])
  @nestAccessControl.UseRoles({
    resource: "TestEntity1",
    action: "read",
    possession: "any",
  })
  async testEntity1s(
    @graphql.Args() args: TestEntity1FindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<TestEntity1[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "TestEntity1",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => TestEntity1, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "TestEntity1",
    action: "read",
    possession: "own",
  })
  async testEntity1(
    @graphql.Args() args: TestEntity1FindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<TestEntity1 | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "TestEntity1",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => TestEntity1)
  @nestAccessControl.UseRoles({
    resource: "TestEntity1",
    action: "delete",
    possession: "any",
  })
  async deleteTestEntity1(
    @graphql.Args() args: DeleteTestEntity1Args
  ): Promise<TestEntity1 | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
