/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { TestEntity1WhereInput } from "./TestEntity1WhereInput";
import { Type } from "class-transformer";
import { TestEntity1OrderByInput } from "./TestEntity1OrderByInput";

@ArgsType()
class TestEntity1FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => TestEntity1WhereInput,
  })
  @Field(() => TestEntity1WhereInput, { nullable: true })
  @Type(() => TestEntity1WhereInput)
  where?: TestEntity1WhereInput;

  @ApiProperty({
    required: false,
    type: TestEntity1OrderByInput,
  })
  @Field(() => TestEntity1OrderByInput, { nullable: true })
  @Type(() => TestEntity1OrderByInput)
  orderBy?: TestEntity1OrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { TestEntity1FindManyArgs };
